[package]
name = "rust-caster"
version = "0.14.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]

[dependencies]
ansi_term = "0.11.0"
docopt = "1.0.1"
env_logger = "0.5.13"
log = "0.4.5"
rust_cast = "0.14.0"
serde = "1.0.80"
serde_derive = "1.0.80"
