[package]
name = "rust-caster"
version = "0.12.1"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]

[dependencies]
ansi_term = "0.11.0"
docopt = "0.8.3"
env_logger = "0.5.10"
log = "0.4.1"
rust_cast = "0.12.1"
serde = "1.0.52"
serde_derive = "1.0.52"
